/** Zone definitions for Orange World ULTRA bundles (country lists shared across World SKUs). */
export type OrangeWorldZone = {
  id: "zone1" | "zone2" | "zone3" | "zone4" | "zone5" | "zone6";
  label: string;
  countries: string[];
};

export const ORANGE_WORLD_ZONES: OrangeWorldZone[] = [
  {
    id: "zone1",
    label: "Zone 1",
    countries: [
      "EU (including UK)",
      "Switzerland",
      "USA",
      "Canada",
      "South Africa",
      "Albania",
      "Algeria",
      "Saudi Arabia",
      "Argentina",
      "Armenia",
      "Australia",
      "Tasmania",
      "Bangladesh",
      "Benin",
      "Belarus",
      "Bosnia and Herzegovina",
      "Botswana",
      "Brazil",
      "Burkina Faso",
      "Cambodia",
      "Cameroon",
      "Central African Republic",
      "Chile",
      "China",
      "Hong Kong",
      "Macao",
      "Colombia",
      "Democratic Republic of the Congo (Congo-Kinshasa)",
      "South Korea",
      "Costa Rica",
      "Ivory Coast",
      "United Arab Emirates",
      "Ecuador",
      "Gabon",
      "Georgia",
      "Guatemala",
      "Guinea-Bissau",
      "Guinea Conakry",
      "Honduras",
      "India",
      "Indonesia",
      "Israel",
      "Japan",
      "Jordan",
      "Laos",
      "North Macedonia",
      "Madagascar",
      "Malaysia",
      "Mali",
      "Morocco",
      "Mexico",
      "Moldova",
      "Montenegro",
      "Nicaragua",
      "Chatham Islands",
      "New Zealand",
      "Uzbekistan",
      "Pakistan",
      "Peru",
      "Philippines",
      "Puerto Rico",
      "Russia",
      "El Salvador",
      "Senegal",
      "Serbia",
      "Singapore",
      "Taiwan",
      "Thailand",
      "Tunisia",
      "Turkey",
      "Northern Cyprus (Turkish)",
      "Ukraine",
      "Uruguay",
      "Vietnam",
      "Dominican Republic",
      "Egypt",
      "French Polynesia",
      "Mauritius",
      "Qatar",
    ],
  },
  {
    id: "zone2",
    label: "Zone 2",
    countries: ["Bahrain", "New Caledonia", "Kenya", "Kuwait", "Nepal", "Oman", "Paraguay", "Sri Lanka"],
  },
  {
    id: "zone3",
    label: "Zone 3",
    countries: [
      "Bolivia",
      "Congo (Congo-Brazzaville)",
      "Ethiopia",
      "Ghana",
      "Jamaica",
      "Liberia",
      "Mozambique",
      "Niger",
      "Nigeria",
      "Uganda",
      "Rwanda",
      "Seychelles",
      "Sierra Leone",
      "Tanzania",
      "Chad",
      "Zambia",
    ],
  },
  {
    id: "zone4",
    label: "Zone 4",
    countries: [
      "Azerbaijan",
      "Brunei",
      "Fiji",
      "Iraq",
      "Lesotho",
      "Mauritania",
      "Mongolia",
      "Palestine",
      "Panama",
      "Papua New Guinea",
      "Tonga",
      "Vanuatu",
    ],
  },
  {
    id: "zone5",
    label: "Zone 5",
    countries: [
      "Afghanistan",
      "Antigua and Barbuda",
      "Aruba",
      "Bahamas",
      "Barbados",
      "Cape Verde",
      "Cuba",
      "Curaçao",
      "Bonaire",
      "Saba",
      "Sint Eustatius",
      "Sint Maarten (Dutch part)",
      "Greenland",
      "Grenada",
      "Equatorial Guinea",
      "Guyana",
      "Kazakhstan",
      "Lebanon",
      "Anguilla",
      "Montserrat",
      "Turks and Caicos Islands",
      "British Virgin Islands",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Vincent and the Grenadines",
      "Suriname",
      "Togo",
      "Trinidad and Tobago",
      "Venezuela",
      "Yemen",
    ],
  },
  {
    id: "zone6",
    label: "Zone 6",
    countries: ["Rest of world"],
  },
];
