/** ISO 3166-2 style codes where available; label is display name. */
export type ShippingSubdivision = { code: string; label: string };

const SUBDIVISIONS: Record<string, ShippingSubdivision[]> = {
  US: [
    { code: "AL", label: "Alabama" },
    { code: "AK", label: "Alaska" },
    { code: "AZ", label: "Arizona" },
    { code: "AR", label: "Arkansas" },
    { code: "CA", label: "California" },
    { code: "CO", label: "Colorado" },
    { code: "CT", label: "Connecticut" },
    { code: "DE", label: "Delaware" },
    { code: "DC", label: "District of Columbia" },
    { code: "FL", label: "Florida" },
    { code: "GA", label: "Georgia" },
    { code: "HI", label: "Hawaii" },
    { code: "ID", label: "Idaho" },
    { code: "IL", label: "Illinois" },
    { code: "IN", label: "Indiana" },
    { code: "IA", label: "Iowa" },
    { code: "KS", label: "Kansas" },
    { code: "KY", label: "Kentucky" },
    { code: "LA", label: "Louisiana" },
    { code: "ME", label: "Maine" },
    { code: "MD", label: "Maryland" },
    { code: "MA", label: "Massachusetts" },
    { code: "MI", label: "Michigan" },
    { code: "MN", label: "Minnesota" },
    { code: "MS", label: "Mississippi" },
    { code: "MO", label: "Missouri" },
    { code: "MT", label: "Montana" },
    { code: "NE", label: "Nebraska" },
    { code: "NV", label: "Nevada" },
    { code: "NH", label: "New Hampshire" },
    { code: "NJ", label: "New Jersey" },
    { code: "NM", label: "New Mexico" },
    { code: "NY", label: "New York" },
    { code: "NC", label: "North Carolina" },
    { code: "ND", label: "North Dakota" },
    { code: "OH", label: "Ohio" },
    { code: "OK", label: "Oklahoma" },
    { code: "OR", label: "Oregon" },
    { code: "PA", label: "Pennsylvania" },
    { code: "RI", label: "Rhode Island" },
    { code: "SC", label: "South Carolina" },
    { code: "SD", label: "South Dakota" },
    { code: "TN", label: "Tennessee" },
    { code: "TX", label: "Texas" },
    { code: "UT", label: "Utah" },
    { code: "VT", label: "Vermont" },
    { code: "VA", label: "Virginia" },
    { code: "WA", label: "Washington" },
    { code: "WV", label: "West Virginia" },
    { code: "WI", label: "Wisconsin" },
    { code: "WY", label: "Wyoming" },
  ],
  CA: [
    { code: "AB", label: "Alberta" },
    { code: "BC", label: "British Columbia" },
    { code: "MB", label: "Manitoba" },
    { code: "NB", label: "New Brunswick" },
    { code: "NL", label: "Newfoundland and Labrador" },
    { code: "NS", label: "Nova Scotia" },
    { code: "NT", label: "Northwest Territories" },
    { code: "NU", label: "Nunavut" },
    { code: "ON", label: "Ontario" },
    { code: "PE", label: "Prince Edward Island" },
    { code: "QC", label: "Quebec" },
    { code: "SK", label: "Saskatchewan" },
    { code: "YT", label: "Yukon" },
  ],
  AU: [
    { code: "ACT", label: "Australian Capital Territory" },
    { code: "NSW", label: "New South Wales" },
    { code: "NT", label: "Northern Territory" },
    { code: "QLD", label: "Queensland" },
    { code: "SA", label: "South Australia" },
    { code: "TAS", label: "Tasmania" },
    { code: "VIC", label: "Victoria" },
    { code: "WA", label: "Western Australia" },
  ],
  DE: [
    { code: "BW", label: "Baden-Württemberg" },
    { code: "BY", label: "Bavaria" },
    { code: "BE", label: "Berlin" },
    { code: "BB", label: "Brandenburg" },
    { code: "HB", label: "Bremen" },
    { code: "HH", label: "Hamburg" },
    { code: "HE", label: "Hesse" },
    { code: "MV", label: "Mecklenburg-Vorpommern" },
    { code: "NI", label: "Lower Saxony" },
    { code: "NW", label: "North Rhine-Westphalia" },
    { code: "RP", label: "Rhineland-Palatinate" },
    { code: "SL", label: "Saarland" },
    { code: "SN", label: "Saxony" },
    { code: "ST", label: "Saxony-Anhalt" },
    { code: "SH", label: "Schleswig-Holstein" },
    { code: "TH", label: "Thuringia" },
  ],
  GB: [
    { code: "ENG", label: "England" },
    { code: "SCT", label: "Scotland" },
    { code: "WLS", label: "Wales" },
    { code: "NIR", label: "Northern Ireland" },
  ],
  FR: [
    { code: "ARA", label: "Auvergne-Rhône-Alpes" },
    { code: "BFC", label: "Bourgogne-Franche-Comté" },
    { code: "BRE", label: "Brittany" },
    { code: "CVL", label: "Centre-Val de Loire" },
    { code: "COR", label: "Corsica" },
    { code: "GES", label: "Grand Est" },
    { code: "HDF", label: "Hauts-de-France" },
    { code: "IDF", label: "Île-de-France" },
    { code: "NOR", label: "Normandy" },
    { code: "NAQ", label: "Nouvelle-Aquitaine" },
    { code: "OCC", label: "Occitanie" },
    { code: "PDL", label: "Pays de la Loire" },
    { code: "PAC", label: "Provence-Alpes-Côte d'Azur" },
  ],
  IT: [
    { code: "ABR", label: "Abruzzo" },
    { code: "BAS", label: "Basilicata" },
    { code: "CAL", label: "Calabria" },
    { code: "CAM", label: "Campania" },
    { code: "EMR", label: "Emilia-Romagna" },
    { code: "FVG", label: "Friuli-Venezia Giulia" },
    { code: "LAZ", label: "Lazio" },
    { code: "LIG", label: "Liguria" },
    { code: "LOM", label: "Lombardy" },
    { code: "MAR", label: "Marche" },
    { code: "MOL", label: "Molise" },
    { code: "PMN", label: "Piedmont" },
    { code: "PUG", label: "Apulia" },
    { code: "SAR", label: "Sardinia" },
    { code: "SIC", label: "Sicily" },
    { code: "TOS", label: "Tuscany" },
    { code: "TAA", label: "Trentino-Alto Adige" },
    { code: "UMB", label: "Umbria" },
    { code: "VDA", label: "Aosta Valley" },
    { code: "VEN", label: "Veneto" },
  ],
  ES: [
    { code: "AN", label: "Andalusia" },
    { code: "AR", label: "Aragon" },
    { code: "AS", label: "Asturias" },
    { code: "IB", label: "Balearic Islands" },
    { code: "PV", label: "Basque Country" },
    { code: "CN", label: "Canary Islands" },
    { code: "CB", label: "Cantabria" },
    { code: "CL", label: "Castile and León" },
    { code: "CM", label: "Castilla-La Mancha" },
    { code: "CT", label: "Catalonia" },
    { code: "EX", label: "Extremadura" },
    { code: "GA", label: "Galicia" },
    { code: "MD", label: "Madrid" },
    { code: "MC", label: "Murcia" },
    { code: "NC", label: "Navarre" },
    { code: "RI", label: "La Rioja" },
    { code: "VC", label: "Valencian Community" },
  ],
  MX: [
    { code: "AGU", label: "Aguascalientes" },
    { code: "BCN", label: "Baja California" },
    { code: "BCS", label: "Baja California Sur" },
    { code: "CAM", label: "Campeche" },
    { code: "CHP", label: "Chiapas" },
    { code: "CHH", label: "Chihuahua" },
    { code: "CMX", label: "Mexico City" },
    { code: "COA", label: "Coahuila" },
    { code: "COL", label: "Colima" },
    { code: "DUR", label: "Durango" },
    { code: "GUA", label: "Guanajuato" },
    { code: "GRO", label: "Guerrero" },
    { code: "HID", label: "Hidalgo" },
    { code: "JAL", label: "Jalisco" },
    { code: "MEX", label: "State of Mexico" },
    { code: "MIC", label: "Michoacán" },
    { code: "MOR", label: "Morelos" },
    { code: "NAY", label: "Nayarit" },
    { code: "NLE", label: "Nuevo León" },
    { code: "OAX", label: "Oaxaca" },
    { code: "PUE", label: "Puebla" },
    { code: "QUE", label: "Querétaro" },
    { code: "ROO", label: "Quintana Roo" },
    { code: "SLP", label: "San Luis Potosí" },
    { code: "SIN", label: "Sinaloa" },
    { code: "SON", label: "Sonora" },
    { code: "TAB", label: "Tabasco" },
    { code: "TAM", label: "Tamaulipas" },
    { code: "TLA", label: "Tlaxcala" },
    { code: "VER", label: "Veracruz" },
    { code: "YUC", label: "Yucatán" },
    { code: "ZAC", label: "Zacatecas" },
  ],
  BR: [
    { code: "AC", label: "Acre" },
    { code: "AL", label: "Alagoas" },
    { code: "AP", label: "Amapá" },
    { code: "AM", label: "Amazonas" },
    { code: "BA", label: "Bahia" },
    { code: "CE", label: "Ceará" },
    { code: "DF", label: "Federal District" },
    { code: "ES", label: "Espírito Santo" },
    { code: "GO", label: "Goiás" },
    { code: "MA", label: "Maranhão" },
    { code: "MT", label: "Mato Grosso" },
    { code: "MS", label: "Mato Grosso do Sul" },
    { code: "MG", label: "Minas Gerais" },
    { code: "PA", label: "Pará" },
    { code: "PB", label: "Paraíba" },
    { code: "PR", label: "Paraná" },
    { code: "PE", label: "Pernambuco" },
    { code: "PI", label: "Piauí" },
    { code: "RJ", label: "Rio de Janeiro" },
    { code: "RN", label: "Rio Grande do Norte" },
    { code: "RS", label: "Rio Grande do Sul" },
    { code: "RO", label: "Rondônia" },
    { code: "RR", label: "Roraima" },
    { code: "SC", label: "Santa Catarina" },
    { code: "SP", label: "São Paulo" },
    { code: "SE", label: "Sergipe" },
    { code: "TO", label: "Tocantins" },
  ],
  IN: [
    { code: "AN", label: "Andaman and Nicobar Islands" },
    { code: "AP", label: "Andhra Pradesh" },
    { code: "AR", label: "Arunachal Pradesh" },
    { code: "AS", label: "Assam" },
    { code: "BR", label: "Bihar" },
    { code: "CH", label: "Chandigarh" },
    { code: "CT", label: "Chhattisgarh" },
    { code: "DL", label: "Delhi" },
    { code: "GA", label: "Goa" },
    { code: "GJ", label: "Gujarat" },
    { code: "HR", label: "Haryana" },
    { code: "HP", label: "Himachal Pradesh" },
    { code: "JK", label: "Jammu and Kashmir" },
    { code: "JH", label: "Jharkhand" },
    { code: "KA", label: "Karnataka" },
    { code: "KL", label: "Kerala" },
    { code: "MP", label: "Madhya Pradesh" },
    { code: "MH", label: "Maharashtra" },
    { code: "MN", label: "Manipur" },
    { code: "ML", label: "Meghalaya" },
    { code: "MZ", label: "Mizoram" },
    { code: "NL", label: "Nagaland" },
    { code: "OR", label: "Odisha" },
    { code: "PB", label: "Punjab" },
    { code: "RJ", label: "Rajasthan" },
    { code: "SK", label: "Sikkim" },
    { code: "TN", label: "Tamil Nadu" },
    { code: "TG", label: "Telangana" },
    { code: "TR", label: "Tripura" },
    { code: "UP", label: "Uttar Pradesh" },
    { code: "UT", label: "Uttarakhand" },
    { code: "WB", label: "West Bengal" },
  ],
  NL: [
    { code: "DR", label: "Drenthe" },
    { code: "FL", label: "Flevoland" },
    { code: "FR", label: "Friesland" },
    { code: "GE", label: "Gelderland" },
    { code: "GR", label: "Groningen" },
    { code: "LI", label: "Limburg" },
    { code: "NB", label: "North Brabant" },
    { code: "NH", label: "North Holland" },
    { code: "OV", label: "Overijssel" },
    { code: "UT", label: "Utrecht" },
    { code: "ZE", label: "Zeeland" },
    { code: "ZH", label: "South Holland" },
  ],
  CH: [
    { code: "AG", label: "Aargau" },
    { code: "BE", label: "Bern" },
    { code: "ZH", label: "Zürich" },
    { code: "GE", label: "Geneva" },
    { code: "VD", label: "Vaud" },
    { code: "TI", label: "Ticino" },
  ],
  AT: [
    { code: "W", label: "Vienna" },
    { code: "NÖ", label: "Lower Austria" },
    { code: "OÖ", label: "Upper Austria" },
    { code: "ST", label: "Styria" },
    { code: "T", label: "Tyrol" },
    { code: "V", label: "Vorarlberg" },
    { code: "K", label: "Carinthia" },
    { code: "S", label: "Salzburg" },
    { code: "B", label: "Burgenland" },
  ],
  JP: [
    { code: "13", label: "Tokyo" },
    { code: "27", label: "Osaka" },
    { code: "14", label: "Kanagawa" },
    { code: "23", label: "Aichi" },
    { code: "40", label: "Fukuoka" },
    { code: "01", label: "Hokkaido" },
    { code: "26", label: "Kyoto" },
    { code: "11", label: "Saitama" },
  ],
  KR: [
    { code: "11", label: "Seoul" },
    { code: "26", label: "Busan" },
    { code: "27", label: "Daegu" },
    { code: "28", label: "Incheon" },
    { code: "41", label: "Gyeonggi" },
    { code: "42", label: "Gangwon" },
  ],
  NZ: [
    { code: "AUK", label: "Auckland" },
    { code: "WGN", label: "Wellington" },
    { code: "CAN", label: "Canterbury" },
    { code: "OTA", label: "Otago" },
    { code: "WKO", label: "Waikato" },
  ],
  ZA: [
    { code: "GP", label: "Gauteng" },
    { code: "WC", label: "Western Cape" },
    { code: "KZN", label: "KwaZulu-Natal" },
    { code: "EC", label: "Eastern Cape" },
  ],
};

/** Subdivisions for a country, or null when free-text state/county is used. */
export function getShippingSubdivisions(countryCode: string): ShippingSubdivision[] | null {
  const key = countryCode.trim().toUpperCase();
  if (!(key in SUBDIVISIONS)) return null;
  return SUBDIVISIONS[key] ?? null;
}

export function resolveSubdivisionLabel(countryCode: string, stateCode: string): string {
  const subdivisions = getShippingSubdivisions(countryCode);
  if (!subdivisions) return stateCode.trim();
  const match = subdivisions.find((s) => s.code === stateCode);
  return match?.label ?? stateCode.trim();
}
